name: ikawa_protocol_core
description: Shared IKAWA protocol implementation in pure Dart.
version: 0.1.0
publish_to: "none"
resolution: workspace

environment:
  sdk: "^3.11.5"

dependencies:
  protobuf: ^6.0.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
